__author__ = 'HSM Sharique Hasan'
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
'''
max_term = 4000000
sum = 0
number = 2
sequence = [1, 1]
while number > 0:
    sequence_number = sequence[number-1] + sequence[number-2]
    if sequence_number > max_term:
        break
    elif sequence_number % 2 == 0:
        sum += sequence_number
    sequence.append(sequence_number)
    number += 1
# print('Sequence is:', sequence)
print('Sum is: ', sum)